image:
  tag: gitlab-ci-lint
  context: ""
  dir: ""
  dockerfile: ""
commands:
  gitlab-ci-lint:
    prefix: gitlab-ci-lint
    help: --help
    version: --version
    github: BuBuaBu/gitlab-ci-lint
extra: ""
