include:
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/notifications/pushover.yml'
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/docker/default.yml'

stages:
  - debug
  - lint
  - dependency
  - build
  - test
  - push
  - notify

.docker:functions:
  stage: dependency
  variables:
    DOCKER_BUILD_DIR: function/task/$IMAGE_TAG
    IMAGE_NAME: function
    DOCKER_BUILD_CONTEXT: function/task/$IMAGE_TAG
    DOCKERFILE: Dockerfile
    GIT_STRATEGY: fetch

commander:build:
  extends:
    - .build:functions
    - .docker:functions
  variables:
    IMAGE_TAG: commander

dobi:build:
  extends:
    - .build:functions
    - .docker:functions
  variables:
    IMAGE_TAG: dobi

just:build:
  extends:
    - .build:functions
    - .docker:functions
  variables:
    IMAGE_TAG: just

mask:build:
  extends:
    - .build:functions
    - .docker:functions
  variables:
    IMAGE_TAG: mask

menu_commander:build:
  extends:
    - .build:functions
    - .docker:functions
  variables:
    IMAGE_TAG: menu_commander

navi:build:
  extends:
    - .build:functions
    - .docker:functions
  variables:
    IMAGE_TAG: navi

orbit:build:
  extends:
    - .build:functions
    - .docker:functions
  variables:
    IMAGE_TAG: orbit

robo:build:
  extends:
    - .build:functions
    - .docker:functions
  variables:
    IMAGE_TAG: robo

task:build:
  extends:
    - .build:functions
    - .docker:functions
  variables:
    IMAGE_TAG: task
