policies:
  - type: commit
    spec:
      header:
        length: 89
        imperative: false
        case: lower
        invalidLastCharacters: .
      body:
        required: false
      dco: false
      gpg: false
      spellcheck:
        locale: US
      maximumOfOneCommit: false
      # conventional:
      #   types:
      #     - chore
      #     - docs
      #     - perf
      #     - refactor
      #     - style
      #     - test
      #   scopes:
      #     - policy
      #   descriptionLength: 72
  - type: license
    spec:
      skipPaths:
        - .git/
        - .build*/
      includeSuffixes:
        - .ext
      excludeSuffixes:
        - .exclude-ext-prefix.ext
      header: |
        This is the contents of a license header.
