build:
  - name: Setup
    image: donaldrich/builder:latest
    commands:
      - ["ginstall.sh", "shellcheck", "latest"]
      - ["upx", "/usr/local/bin/shellcheck"]
      - ["mv", "/usr/local/bin/shellcheck", "/tmp"]
      - ["chmod", "a+x", "/tmp/shellcheck"]
    user: root
    mounts:
      - /usr/bin/:/tmp:w
  - name: hadolint
    image: hadolint/hadolint:latest
    commands:
      - ["mv", "/bin/hadolint", "/tmp"]
      - ["chmod", "a+x", "/tmp/hadolint"]
    user: root
    mounts:
      - /usr/bin/:/tmp:w
