include:
  - project: donaldrich/modular-gitlab-ci
    file: templates/default.yml
  # - project: donaldrich/modular-gitlab-ci
  #   file: function/repo/auto-push.yml
  - project: donaldrich/modular-gitlab-ci
    file: function/repo/semantic-release.yml
  - local: .meta/pipelines.gitlab-ci.yml

cache:
  # untracked: true
  paths:
    - .meta/snippets/

stages:
  - pre
  - lint
  - debug
  - build
  - documentation
  - deploy
  - post

variables:
  DISABLE_LINTING: "true"
  DISABLE_SAST: "true"
  DISABLE_HEALTHCHECKS: "true"
  PUSHOVER_ID: $CI_PROJECT_TITLE
