include:
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/analysis/sast.yml'
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/lint/default.yml'

stages:
  - lint
  - debug
  - builder
  - dependency
  - build
  - test
  - push
  - notify

function:functions:
  stage: dependency
  trigger:
    include: function/function/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
      - "function/function/*"
      when: on_success
    - if: '$TRIGGER_VAR1 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "function"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "function" && $TRIGGER_VAR2 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "function" && $TRIGGER_VAR2 == "function"'
      when: on_success

utility:functions:
  stage: dependency
  trigger:
    include: function/utility/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
      - "function/utility/*"
      when: on_success
    - if: '$TRIGGER_VAR1 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "function"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "utility" && $TRIGGER_VAR2 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "utility" && $TRIGGER_VAR2 == "function"'
      when: on_success

task:functions:
  stage: dependency
  trigger:
    include: function/task/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
      - "function/task/*"
      when: on_success
    - if: '$TRIGGER_VAR1 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "function"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "task" && $TRIGGER_VAR2 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "task" && $TRIGGER_VAR2 == "function"'
      when: on_success

lint:functions:
  stage: dependency
  trigger:
    include: function/lint/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
      - "function/lint/*"
      when: on_success
    - if: '$TRIGGER_VAR1 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "function"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "lint" && $TRIGGER_VAR2 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "lint" && $TRIGGER_VAR2 == "function"'
      when: on_success

hashicorp:functions:
  stage: dependency
  trigger:
    include: function/hashicorp/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
      - "function/hashicorp/*"
      when: on_success
    - if: '$TRIGGER_VAR1 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "function"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "hashicorp" && $TRIGGER_VAR2 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "hashicorp" && $TRIGGER_VAR2 == "function"'
      when: on_success

docker:functions:
  stage: dependency
  trigger:
    include: function/docker/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
      - "function/docker/*"
      when: on_success
    - if: '$TRIGGER_VAR1 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "function"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "docker" && $TRIGGER_VAR2 == "all"'
      when: on_success
    - if: '$TRIGGER_VAR1 == "docker" && $TRIGGER_VAR2 == "function"'
      when: on_success

