ignored:
  - DL3007 # Using latest is prone to errors if the image will ever update. Pin the version explicitly to a release tag
  - DL3006 # Always tag the version of an image explicitly
  - DL3008 # Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
  - DL3013 # Pin versions in pip. Instead of `pip install <package>` use `pip install <package>==<version>`
  - DL3016 # Pin versions in npm. Instead of `npm install <package>` use `npm install <package>@<version>
  - DL3018 #Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>
  - DL3022 # COPY --from should reference a previously defined FROM alias
  - DL3028 # Pin versions in gem install. Instead of `gem install <gem>` use `gem install <gem>:<version>`

  # temp

  - DL4006 # Set the SHELL option -o pipefail before RUN with a pipe in it
