repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        exclude: mkdocs.yml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=no"]
  - repo: local
    hooks:
      - id: gitleaks
        name: gitleaks
        entry: zricethezav/gitleaks
        language: docker_image
  - repo: https://gitlab.com/donaldrich/function-as-a-container
    rev: master
    hooks:
      - id: lint-markdown-markdownlint
      # - id: lint-dockerfile-hadolint
      - id: gitleaks
      # - id: lint-markdown-misspell
  - repo: https://github.com/prettier/prettier
    rev: master
    hooks:
      - id: prettier
