# Secret Detection
- id: secrets-gitleaks
  name: Checks commits for secrets w gitleaks
  description: Checks commits for secrets w gitleaks
  entry: zricethezav/gitleaks
  args: ["--verbose", "--pretty"]
  pass_filenames: false
  language: docker_image
  verbose: true
- id: secrets-detect-secrets
  name: Detect secrets
  description: Detects high entropy strings that are likely to be passwords.
  entry: --entrypoint detect-secrets donaldrich/function:detect-secrets
  args: ["scan", "--base64-limit", "4.5", "--hex-limit", "3"]
  # args: [--baseline, ci/secrets.baseline]
  language: docker_image
- id: docker-lint-dockerfile_lint
  name: dockerfile_lint
  entry: --entrypoint dockerfile_lint donaldrich/function:dockerfile_lint
  language: docker_image
  args: [--dockerfile]
  files: Dockerfile.*
- id: docker-lint-dockerfilelint
  name: Lint Dockerfiles w dockerfilelint linter
  entry: --entrypoint dockerfilelint donaldrich/function:dockerfilelint
  language: docker_image
  files: Dockerfile.*
- id: docker-lint-hadolint
  name: Lint Dockerfiles w hadolint
  description: Lint Dockerfiles w hadolint
  language: docker_image
  entry: hadolint/hadolint hadolint
  files: Dockerfile.*
- id: lint-markdown-markdownlint
  name: Lint Markdown w markdownlint
  description: Lint Markdown w markdownlint
  language: docker_image
  entry: donaldrich/function:markdown markdownlint
  types: [markdown]
  exclude: .meta/snippets/layout.md
- id: lint-markdown-remarklint
  name: Lint markdown w remark
  description: remark-lint
  language: docker_image
  entry: pipelinecomponents/remark-lint remark
  args: ["."]
  types: [markdown]
- id: mdspell
  name: mdspell
  description: mdspell
  language: docker_image
  entry: --entrypoint mdspell pipelinecomponents/markdown-spellcheck mdspell
  args: ["--report", "**/*.md"]
  types: [markdown]
- id: lint-markdown-misspell
  name: misspell
  entry: --entrypoint misspell donaldrich/function:misspell
  language: docker_image
  args: [-w, "."]
  types: [markdown]
- id: packer-fix
  name: Fix Packer template(s) with backwards incompatibilities
  entry: hashicorp/packer:light fix
  language: docker_image
  types: [json]
  files: ^packer.json$
  always_run: false
  verbose: false
  pass_filenames: true
  description: Attempts to fix incompatibilities in a template
- id: packer-validate
  name: Validate Packer template(s)
  entry: hashicorp/packer:light validate
  language: docker_image
  types: [json]
  files: ^packer.json$
  always_run: false
  verbose: false
  pass_filenames: true
  description: Validates a template against builders, provisioners
  args: [-syntax-only, "."]
- id: task-tusk
  name: tusk
  description: tusk
  entry: --entrypoint tusk donaldrich/function:task
  language: docker_image
  pass_filenames: false
  verbose: true
- id: shell-lint-shellcheck
  name: lint-shell-shellcheck
  entry: koalaman/shellcheck:stable
  language: docker_image
  types: [shell]
- id: shell-lint-shfmt
  name: lint-shell-shfmt
  entry: --entrypoint shfmt donaldrich/function:shell
  language: docker_image
  args: ["-w"]
  types: [shell]
- id: shell-lint-bashate
  name: bashate
  entry: --entrypoint bashate donaldrich/function:shell
  language: docker_image
  types: [shell]
# - id: terraform-fmt-check
#   name: Terraform fmt
#   description: Rewrites all Terraform configuration files to a canonical format.
#   entry: --entrypoint terraform donaldrich/function:terraform
#   args: ["fmt", "-check", "-recursive"]
#   pass_filenames: false
#   language: docker_image
#   files: (\.tf|\.tfvars)$
#   exclude: \.terraform\/.*$
# types: [terraform]
- id: terraform-fmt
  name: Terraform fmt
  description: Rewrites all Terraform configuration files to a canonical format.
  entry: --entrypoint terraform donaldrich/function:terraform
  args: ["fmt", "-recursive"]
  pass_filenames: false
  language: docker_image
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$
- id: terraform-tflint
  name: Terraform validate with tflint
  description: Validates all Terraform configuration files with TFLint.
  entry: --entrypoint tflint donaldrich/function:terraform
  pass_filenames: false
  language: docker_image
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$
- id: terraform-tfsec
  name: Terraform validate with tfsec
  description: Validates all Terraform configuration files with TFLint.
  entry: --entrypoint tfsec donaldrich/function:terraform
  pass_filenames: false
  language: docker_image
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$
- id: terraform-validate
  name: Terraform validate with tfsec
  description: Validates all Terraform configuration files with TFLint.
  entry: --entrypoint terraform donaldrich/function:terraform
  args: ["validate"]
  pass_filenames: false
  language: docker_image
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$
- id: repo-semantic-release
  name: repo-semver-semantic-release
  entry: --entrypoint semantic-release donaldrich/function:semver
  language: docker_image
  args: ["--generate-notes", "false", "--dry-run"]
  pass_filenames: false
  verbose: true
- id: repo-policy-commitizen
  name: commitizen check
  entry: --entrypoint cz donaldrich/function:semver
  language: docker_image
  args: ["check"]
  # pass_filenames: false
  verbose: true
  # stages: [commit-msg]
- id: repo-policy-commitlint
  name: repo-policy-commitlint
  entry: --entrypoint commitlint donaldrich/function:semver
  language: docker_image
  args: ["--edit"]
  pass_filenames: false
  stages: [commit-msg]
- id: repo-policy-conform
  name: repo-policy-conform
  entry: --entrypoint conform donaldrich/function:conform
  language: docker_image
  args: ["enforce"]
  verbose: true
  pass_filenames: false
- id: repo-prettier
  name: repo-prettier
  entry: --entrypoint prettier donaldrich/function:prettier
  language: docker_image
  args: ["--write", "--list-different", "--ignore-unknown"]
- id: prettier
  name: prettier
  entry: --entrypoint prettier donaldrich/function:prettier
  language: docker_image
  args: ["--write", "--list-different", "--ignore-unknown"]
- id: yaml-lint-yamllint
  name: Lint YAML w yamllint
  description: Lint YAML w yamllint
  language: docker_image
  entry: --entrypoint yamllint pipelinecomponents/yamllint
  args: [--format, parsable, --strict]
  types: [yaml]
- id: sort-yaml-yml_sorter
  name: Sort YAML files
  description: This hook sorts YAML files
  entry: --entrypoint yml-sorter -i
  language: docker_image
  types: [yaml]
  # files: "(yml|yaml)"
  args: ["-i"]
- id: yaml-yq
  name: Use yq
  description: yq is a lightweight and portable command-line YAML processo
  entry: --entrypoint yq mikefarah/yq
  args: ["merge", "-a"]
  language: docker_image
- id: yaml-ytt
  name: Use ytt
  description: yq is a lightweight and portable command-line YAML processo
  entry: --entrypoint ytt donaldrich/function:yaml
  language: docker_image
