repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-yaml
        exclude: mkdocs.yml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: lint-markdown-misspell
        name: misspell
        entry: --entrypoint misspell donaldrich/function:misspell
        language: docker_image
        args: [-w, "."]
        types: [markdown]
  - repo: https://gitlab.com/donaldrich/function-as-a-container
    rev: 718ef00594a593cd37494030f0138386e4af5cd9
    hooks:
      # - id: lint-markdown-markdownlint
      # - id: lint-dockerfile-hadolint
      - id: gitleaks
      # - id: lint-markdown-misspell
  - repo: https://github.com/prettier/prettier
    rev: 2.1.1
    hooks:
      - id: prettier
