repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-yaml
        exclude: mkdocs.yml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
  # - repo: https://github.com/prettier/prettier
  #   rev: 2.1.2
  #   hooks:
  #     - id: prettier
  #       verbose: true
  # - repo: https://gitlab.com/donaldrich/function-as-a-container
  #   rev: v1.0.3
  #   hooks:
  #     - id: repo-policy-commitlint

  # - id: repo-semver-semantic-release
  #   name: repo-semver-semantic-release
  #   entry: --entrypoint semantic-release donaldrich/function:semantic-release
  #   language: docker_image
  #   args: ["--generate-notes", "false" ,"--dry-run"]
  #   pass_filenames: false
  #   verbose: true

  # - repo: https://github.com/talos-systems/conform
  #   rev: v0.1.0-alpha.20
  #   hooks:
  #     - id: conform
  #       stages:
  #         - commit-msg

  #     -   id: check-x
  #         name: Check X
  #         entry: ./run-all.sh
  #         language: script
