"0":
  id: docker-lint-hadolint
  name: Lint Dockerfiles w hadolint
  description: Lint Dockerfiles w hadolint
  language: docker_image
  entry: hadolint/hadolint hadolint
  files: Dockerfile.*
  args:
    - "scan"
"1":
  id: docker-lint-hadolint
  name: Lint Dockerfiles w hadolint
  description: Lint Dockerfiles w hadolint
  language: docker_image
  entry: hadolint/hadolint hadolint
  files: Dockerfile.*
"2":
  id: docker-lint-hadolint
  name: Lint Dockerfiles w hadolint
  description: Lint Dockerfiles w hadolint
  language: docker_image
  entry: hadolint/hadolint hadolint
  files: Dockerfile.*
