repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-yaml
        exclude: mkdocs.yml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/talos-systems/conform
    rev: master
    hooks:
      - id: conform
        stages:
          - commit-msg
  - repo: local
    hooks:
      - id: gitleaks
        name: Gitleaks
        entry: zricethezav/gitleaks
        language: docker_image
      # - id: conform
      #   name: conform
      #   entry: --entrypoint "conform enforce" donaldrich/function:conform
      #   language: docker_image
      # args: ["enforce"]
  # -   repo: local
  #     hooks:
  #     -   id: check-x
  #         name: Check X
  #         entry: ./run-all.sh
  #         language: script
  - repo: https://github.com/prettier/prettier
    rev: 2.1.2
    hooks:
      - id: prettier
