repos:
  - repo: https://github.com/prettier/prettier
    rev: 7c5a7d3c747c73b19f9f44757a7a75e9169afce4
    hooks:
      - id: prettier
        stages: [commit]
  - repo: local
    hooks:
      # - id: tusk-regenerate
      #   name: tusk-regenerate
      #   entry: tusk clean-repo
      #   language: system
      #   pass_filenames: false
      - id: hook-test
        name: Use yq
        description: Use yq
        entry: --entrypoint yq mikefarah/yq
        args: ["merge", "-a"]
        files: git-hooks.yml
        language: docker_image
        verbose: true
        log_file: .pre-commit-hooks.yaml
        stages: [manual]

      # - id: tusk-template
      #   name: tusk-template
      #   entry: tusk template
      #   language: system
      #   pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 5bd9e74adfb59d8e14c8a88c36511eb60c59b36e
    hooks:
      - id: check-added-large-files
        stages: [commit]
      - id: check-executables-have-shebangs
      - id: check-yaml
        exclude: mkdocs.yml
      - id: detect-private-key
        stages: [commit]
      - id: end-of-file-fixer
      # - id: mixed-line-ending
      #   args: ["--fix=lf"]

  - repo: https://gitlab.com/donaldrich/function-as-a-container
    rev: d2cd61867e4f24e19090b21ad5eb61f4a01730ef
    hooks:
      - id: shell-lint-shellcheck
        stages: [commit]
      - id: shell-lint-shfmt
        stages: [commit]
      #   verbose: true
      # - id: shell-lint-bashate
      #   stages: [commit]
      #   verbose: true
      - id: secrets-detect-secrets
        stages: [commit]
      - id: secrets-gitleaks
        stages: [commit]
      - id: yaml-lint-yamllint
        stages: [commit]
      - id: docker-lint-hadolint
        exclude: Dockerfile.tmpl.*

  # - repo: https://github.com/commitizen-tools/commitizen
  #   rev: v2.4.0
  #   hooks:
  #     - id: commitizen
  #       stages: [commit-msg]

  # stages: [commit-msg]
  # - repo: https://github.com/talos-systems/conform
  #   rev: v0.1.0-alpha.20
  #   hooks:
  #     - id: conform
  #       stages:
  #         - commit-msg

  # function-yaml-yq
  # - id: repo-policy-commitlint
  #   stages: [commit-msg]

  # - id: repo-policy-commitlint
  #   stages: [prepare-commit-msg]

  # - id: repo-policy-commitizen
  #   stages: [prepare-commit-msg]
