repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-yaml
        exclude: mkdocs.yml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: https://gitlab.com/donaldrich/function-as-a-container
    rev: v1.2.3
    hooks:
      - id: lint-shell-shellcheck
      - id: repo-scan-yelp
      - id: repo-scan-gitleaks
      # - id: repo-policy-commitizen
      #   stages: [prepare-commit-msg]
      - id: repo-policy-commitlint
        stages: [commit-msg]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.4.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # - repo: local
  #   hooks:
  #     - id: repo-policy-commitizen
  #       name: commitizen check
  #       entry: --entrypoint cz donaldrich/function:semver
  #       language: docker_image
  #       args: ["commit"]
  #       # pass_filenames: false
  #       verbose: true

  # stages: [commit-msg]
  # - repo: https://github.com/talos-systems/conform
  #   rev: v0.1.0-alpha.20
  #   hooks:
  #     - id: conform
  #       stages:
  #         - commit-msg

  #     -   id: check-x
  #         name: Check X
  #         entry: ./run-all.sh
  #         language: script

  # - repo: https://github.com/prettier/prettier
  #   rev: 2.1.2
  #   hooks:
  #     - id: prettier
        # stages: [prepare-commit-msg]
