repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]

  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v2.2.1
  #   hooks:
  #     - id: prettier
  #       verbose: true

  # - hooks:
  # - args:
  #     - merge
  #     - -a
  #   description: Use yq
  #   entry: --entrypoint yq mikefarah/yq
  #   files: git-hooks.yml
  #   id: hook-test
  #   language: docker_image
  #   log_file: .pre-commit-hooks.yaml
  #   verbose: true
  #   name: Use yq
  #   stages:
  #     - manual
  # - id: spellcheck-misspell
  #   name: misspell
  #   entry: --entrypoint misspell donaldrich/function:misspell
  #   language: docker_image
  #   types: [text]
  #   description: Checks for common misspellings in text files.
  #   args: ["-w", "."]
  #   repo: local


  #   repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v3.3.0
  # - hooks:
  #     - id: secrets-detect-secrets
  #       stages:
  #         - commit
  #     - id: secrets-gitleaks
  #       stages:
  #         - commit
  #     - id: yaml-yamllint
  #       stages:
  #         - commit
  #     - exclude: Dockerfile.tmpl.*
  #       id: docker-lint-hadolint
  #   repo: https://gitlab.com/donaldrich/function-as-a-container
  #   rev: v2.2.0
  # - hooks:
  #     - id: commitizen
  #       stages:
  #         - commit-msg
  #   repo: https://github.com/commitizen-tools/commitizen
  #   rev: d8e9badae9d5ab1c088d5bb0932f3977db24d442

  - repo: local
    hooks:
      - id: docker-hadolint
        name: Lint Dockerfiles with hadolint
        description: Lint Dockerfiles w hadolint
        language: docker_image
        entry: hadolint/hadolint hadolint
        files: Dockerfile.*
        exclude: Dockerfile.tmpl.*
      - id: yaml-yamllint
        name: Lint YAML w yamllint
        description: Lint YAML w yamllint
        language: docker_image
        entry: --entrypoint yamllint donaldrich/function:syntax-tools
        args: [--format, parsable, --strict]
        types: [yaml]
