repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-yaml
        exclude: mkdocs.yml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  # - repo: local
  #   hooks:
  #     - id: gitleaks
  #       name: gitleaks
  #       description: Checks commits for secrets
  #       entry: zricethezav/gitleaks
  #       language: docker_image
  #       args: [--repo=/]
  - repo: https://gitlab.com/donaldrich/function-as-a-container
    rev: 1719e2fa2574b7cf7116dfe3c2135246ed2d56c3
    hooks:
      # - id: lint-markdown-markdownlint
      - id: lint-yaml-yamllint
      - id: gitleaks
      # - id: lint-markdown-misspell
  - repo: https://github.com/prettier/prettier
    rev: 2.1.1
    hooks:
      - id: prettier
