branches:
  - "master"
  # - "+([0-9])?(.{+([0-9]),x}).x"
  # - name: "alpha"
  #   prerelease: "alpha"
preset: conventionalcommits
tagFormat: v${version}
repositoryUrl: https://gitlab.com/donaldrich/function-as-a-container.git
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: docs
          # scope: README
          release: patch
        - type: refactor
          release: patch
        - type: perf
          scope: repo
          release: minor
        - type: chore
          release: false
        - scope: auto
          release: false
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING
  - "@semantic-release/gitlab"
# - - "@semantic-release/exec"
#   - verifyConditionsCmd: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#     verifyReleaseCmd: |
#       MAJOR_MINOR_PATCH=${/^((\d+)\.\d+)\.\d+$/.exec(nextRelease.version)}
#       if [ -z $MAJOR_MINOR_PATCH ]; then echo "Only SemVer versions with version core (major.minor.patch) supported!"; exit 1; fi
#     prepareCmd: docker build -t $IMAGE_NAME:latest .
#     publishCmd: |
#       MAJOR_MINOR_PATCH=${/^((\d+)\.\d+)\.\d+$/.exec(nextRelease.version)[0]}
#       MAJOR_MINOR=${      /^((\d+)\.\d+)\.\d+$/.exec(nextRelease.version)[1]}
#       MAJOR=${            /^((\d+)\.\d+)\.\d+$/.exec(nextRelease.version)[2]}
#       docker tag $IMAGE_NAME:latest $IMAGE_NAME:$MAJOR_MINOR_PATCH
#       docker tag $IMAGE_NAME:latest $IMAGE_NAME:$MAJOR_MINOR
#       docker tag $IMAGE_NAME:latest $IMAGE_NAME:$MAJOR
#       docker push $IMAGE_NAME:latest
#       docker push $IMAGE_NAME:$MAJOR_MINOR_PATCH
#       docker push $IMAGE_NAME:$MAJOR_MINOR
#       docker push $IMAGE_NAME:$MAJOR
# - "@semantic-release/github"

# branch: master
# repositoryUrl: https://github.com/bycedric/docker.git
# tagFormat: ${version}

# generateNotes:
#   - path: '@semantic-release/release-notes-generator'
#     preset: peakfijn

# verifyConditions:
#   - '@semantic-release/changelog'
#   - '@semantic-release/npm'
#   - '@semantic-release/github'
#   - semantic-release-git-branches

# prepare:
#   - '@semantic-release/changelog'
#   - path: '@semantic-release/npm'
#     npmPublish: false
#   - path: semantic-release-git-branches
#     branchMerges: [develop, master]
#     message: |-
#       release: create new version ${nextRelease.version}
#       ${nextRelease.notes}
# publish:
#   - '@semantic-release/github'
