branches:
  - "master"
  # - "+([0-9])?(.{+([0-9]),x}).x"
  # - name: "alpha"
  #   prerelease: "alpha"
preset: conventionalcommits
tagFormat: v${version}
repositoryUrl: https://gitlab.com/donaldrich/function-as-a-container.git
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: docs
          # scope: README
          release: patch
        - type: refactor
          release: patch
        - type: perf
          scope: repo
          release: minor
        - type: chore
          release: false
        - scope: auto
          release: false
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING
  - "@semantic-release/gitlab"
  - - "@semantic-release/changelog"
    - changelogFile: .meta/CHANGELOG.md

    # ["@semantic-release/git", {
    #   "assets": ["docs/CHANGELOG.md"]
    # }],
# verifyConditions:
#   - '@semantic-release/changelog'
#   - '@semantic-release/npm'
#   - '@semantic-release/github'
#   - semantic-release-git-branches

# prepare:
#   - '@semantic-release/changelog'
#   - path: '@semantic-release/npm'
#     npmPublish: false
#   - path: semantic-release-git-branches
#     branchMerges: [develop, master]
#     message: |-
#       release: create new version ${nextRelease.version}
#       ${nextRelease.notes}
# publish:
#   - '@semantic-release/github'
