version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "docker"
    directory: "docker"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "files"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
