---
tasks:

  build:
    usage: build docker image
    run: docker build --pull --rm -t function:dockerfilelint .

  test:
    usage: build docker image
    run: docker run -it --rm function:dockerfilelint validate


  dive:
    usage: inspect docker image
    run: docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock donaldrich/function:dive function:dockerfilelint
  validate:
    usage: check package versions
    run:
      - command:
          exec: /dockerfilelint/bin/dockerfilelint --version
          print: "\e[32m/dockerfilelint/bin/dockerfilelint\e[0m"
  help:
    usage: see config options
    run:
      - command:
          exec: /dockerfilelint/bin/dockerfilelint --help
          print: "\e[32m/dockerfilelint/bin/dockerfilelint\e[0m"
