---
tasks:
  build:
    usage: build docker image
    run: docker build --pull --rm -t function:kubernetes .

  test:
    usage: build docker image
    run: docker run -it --rm function:kubernetes validate

  dive:
    usage: inspect docker image
    run: docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock donaldrich/function:dive function:kubernetes
  validate:
    usage: check package versions
    run:
      - command:
          exec: helm version
          print: "\e[32mhelm\e[0m"
  help:
    usage: see config options
    run:
      - command:
          exec: helm help
          print: "\e[32mhelm\e[0m"
