image:
  tag: kubernetes
  context: ""
  dir: ""
  dockerfile: ""
commands:
  helm:
    prefix: helm
    help: help
    version: version
    github: helm/helm
    docs: https://helm.sh
  kompose:
    prefix: kompose
    help: version --help
    version: version
    github: kubernetes/kompose
    docs: http://kompose.io
  kubectl:
    prefix: kubectl
    help: version --help
    version: version
    github: kubectl
  minikube:
    prefix: minikube
    help: version --help
    version: version
    github: minikube
    docs: https://minikube.sigs.k8s.io/docs/
  kind:
    prefix: kind
    help: version --help
    version: version
    github: kubernetes-sigs/kind
    docs: https://kind.sigs.k8s.io
extra: ""
