- id: lint-markdown-markdownlint
  name: Lint Markdown w markdownlint
  description: Lint Markdown w markdownlint
  language: docker_image
  entry: donaldrich/function:markdown markdownlint
  types: [markdown]
  exclude: .meta/snippets/layout.md

- id: lint-markdown-remarklint
  name: Lint markdown w remark
  description: remark-lint
  language: docker_image
  entry: pipelinecomponents/remark-lint remark
  args: ["."]
  types: [markdown]

- id: lint-yaml-yamllint
  name: Lint YAML w yamllint
  description: Lint YAML w yamllint
  language: docker_image
  entry: --entrypoint yamllint pipelinecomponents/yamllint
  # args: ["."]
  args: [--format, parsable, --strict]
  types: [yaml]

- id: prettier
  name: prettier
  entry: --entrypoint prettier donaldrich/function:prettier
  language: docker_image
  args: ["--write", "--list-different", "--ignore-unknown"]

- id: lint-markdown-misspell
  name: misspell
  entry: --entrypoint misspell donaldrich/function:misspell
  language: docker_image
  args: [-w, "."]
  types: [markdown]

- id: mdspell
  name: mdspell
  description: mdspell
  language: docker_image
  entry: --entrypoint mdspell pipelinecomponents/markdown-spellcheck mdspell
  args: ["--report", "**/*.md"]
  types: [markdown]

- id: ansible-lint
  name: ansible-lint
  description: ansible-lint
  language: docker_image
  entry: pipelinecomponents/ansible-lint ansible-lint
  args: ["*"]
  types: [yaml]






# - id: markdownlint_docker
#   name: Markdownlint Docker
#   description: Run markdown lint on your Markdown files using the project docker image
#   language: docker_image
#   files: \.(md|mdown|markdown)$
#   entry: markdownlint/markdownlint mdl





- id: repo-policy-conform
  name: repo-policy-conform
  entry: --entrypoint conform donaldrich/function:conform
  language: docker_image
  args: ["enforce"]
  verbose: true
  pass_filenames: false
  # stages: [commit-msg]

- id: repo-policy-commitizen
  name: commitizen check
  entry: --entrypoint cz donaldrich/function:semver
  language: docker_image
  args: ["check"]
  # pass_filenames: false
  verbose: true
  # stages: [commit-msg]

- id: repo-policy-commitlint
  name: repo-policy-commitlint
  entry: --entrypoint commitlint donaldrich/function:semver
  language: docker_image
  args: ["--edit"]
  pass_filenames: false
  stages: [commit-msg]

- id: repo-prettier
  name: repo-prettier
  entry: --entrypoint prettier donaldrich/function:prettier
  language: docker_image
  args: ["--write", "--list-different", "--ignore-unknown"]

- id: repo-semantic-release
  name: repo-semver-semantic-release
  entry: --entrypoint semantic-release donaldrich/function:semantic-release
  language: docker_image
  args: ["--generate-notes", "false", "--dry-run"]
  pass_filenames: false
  verbose: true

# Secret Detection
- id: repo-scan-gitleaks
  name: Checks commits for secrets w gitleaks
  description: Checks commits for secrets w gitleaks
  entry: zricethezav/gitleaks
  args: ["--verbose", "--pretty"]
  pass_filenames: false
  language: docker_image
  verbose: true

- id: repo-scan-yelp
  name: Detect secrets
  description: Detects high entropy strings that are likely to be passwords.
  entry: --entrypoint detect-secrets donaldrich/function:detect-secrets
  args: ["scan"]
  language: docker_image

- id: repo-scan-detect-secrets
  name: Detect secrets
  description: Detects high entropy strings that are likely to be passwords.
  entry: --entrypoint detect-secrets donaldrich/function:detect-secrets
  args: ['scan', '--base64-limit', '4.5', '--hex-limit', '3']
  # args: [--baseline, ci/secrets.baseline]
  language: docker_image
  # for backward compatibility
  # files: .*


- id: sort-yaml-yml_sorter
  name: Sort YAML files
  description: This hook sorts YAML files
  entry: --entrypoint yml-sorter -i
  language: docker_image
  types: [yaml]
  files: "(yml|yaml)"
  args: ["-i"]
