include:
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/notifications/pushover.yml'
  - project: 'donaldrich/gitlab-ci-templates'
    file: '/docker/default.yml'

stages:
  - debug
  - lint
  - dependency
  - build
  - test
  - push
  - notify

.hashicorp:function:
  stage: dependency
  variables:
    DOCKER_BUILD_DIR: function/hashicorp/$IMAGE_TAG
    IMAGE_ALIAS: hashicorp
    IMAGE_NAME: function
    DOCKER_BUILD_CONTEXT: function/hashicorp/$IMAGE_TAG
    DOCKERFILE: Dockerfile
    GIT_STRATEGY: fetch

packer-builder-arm-image:build:
  extends:
    - .build:functions
    - .hashicorp:function
  variables:
    IMAGE_TAG: packer-builder-arm-image

hashi-helper:build:
  extends:
    - .build:functions
    - .hashicorp:function
  variables:
    IMAGE_TAG: hashi-helper

packer:build:
  extends:
    - .build:functions
    - .hashicorp:function
  variables:
    IMAGE_TAG: packer

packer-builder-arm:build:
  extends:
    - .build:functions
    - .hashicorp:function
  variables:
    IMAGE_TAG: packer-builder-arm

packer-provisioner-goss:build:
  extends:
    - .build:functions
    - .hashicorp:function
  variables:
    IMAGE_TAG: packer-provisioner-goss

tflint:build:
  extends:
    - .build:functions
    - .hashicorp:function
  variables:
    IMAGE_TAG: tflint

tfsec:build:
  extends:
    - .build:functions
    - .hashicorp:function
  variables:
    IMAGE_TAG: tfsec

vault:build:
  extends:
    - .build:functions
    - .hashicorp:function
  variables:
    IMAGE_TAG: vault

vault-sync:build:
  extends:
    - .build:functions
    - .hashicorp:function
  variables:
    IMAGE_TAG: vault-sync

vault-unseal:build:
  extends:
    - .build:functions
    - .hashicorp:function
  variables:
    IMAGE_TAG: vault-unseal
